// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class AveragingGoal {
  constructor() {
    this.samples = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type AveragingGoal
    // Serialize message field [samples]
    bufferInfo = _serializer.int32(obj.samples, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type AveragingGoal
    let tmp;
    let len;
    let data = new AveragingGoal();
    // Deserialize message field [samples]
    tmp = _deserializer.int32(buffer);
    data.samples = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/AveragingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '32c9b10ef9b253faa93b93f564762c8f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 samples
    
    `;
  }

};

module.exports = AveragingGoal;
