// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class AveragingResult {
  constructor() {
    this.mean = 0.0;
    this.std_dev = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type AveragingResult
    // Serialize message field [mean]
    bufferInfo = _serializer.float32(obj.mean, bufferInfo);
    // Serialize message field [std_dev]
    bufferInfo = _serializer.float32(obj.std_dev, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type AveragingResult
    let tmp;
    let len;
    let data = new AveragingResult();
    // Deserialize message field [mean]
    tmp = _deserializer.float32(buffer);
    data.mean = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [std_dev]
    tmp = _deserializer.float32(buffer);
    data.std_dev = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/AveragingResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd5c7decf6df75ffb4367a05c1bcc7612';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float32 mean
    float32 std_dev
    
    `;
  }

};

module.exports = AveragingResult;
