// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class FibonacciGoal {
  constructor() {
    this.order = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type FibonacciGoal
    // Serialize message field [order]
    bufferInfo = _serializer.int32(obj.order, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type FibonacciGoal
    let tmp;
    let len;
    let data = new FibonacciGoal();
    // Deserialize message field [order]
    tmp = _deserializer.int32(buffer);
    data.order = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/FibonacciGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6889063349a00b249bd1661df429d822';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 order
    
    `;
  }

};

module.exports = FibonacciGoal;
