// Auto-generated. Do not edit!

// (in-package actionlib.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class TestFeedback {
  constructor() {
    this.feedback = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type TestFeedback
    // Serialize message field [feedback]
    bufferInfo = _serializer.int32(obj.feedback, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type TestFeedback
    let tmp;
    let len;
    let data = new TestFeedback();
    // Deserialize message field [feedback]
    tmp = _deserializer.int32(buffer);
    data.feedback = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib/TestFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '49ceb5b32ea3af22073ede4a0328249e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 feedback
    
    
    `;
  }

};

module.exports = TestFeedback;
