// Auto-generated. Do not edit!

// (in-package actionlib.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class TestRequestResult {
  constructor() {
    this.the_result = 0;
    this.is_simple_server = false;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type TestRequestResult
    // Serialize message field [the_result]
    bufferInfo = _serializer.int32(obj.the_result, bufferInfo);
    // Serialize message field [is_simple_server]
    bufferInfo = _serializer.bool(obj.is_simple_server, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type TestRequestResult
    let tmp;
    let len;
    let data = new TestRequestResult();
    // Deserialize message field [the_result]
    tmp = _deserializer.int32(buffer);
    data.the_result = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [is_simple_server]
    tmp = _deserializer.bool(buffer);
    data.is_simple_server = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib/TestRequestResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '61c2364524499c7c5017e2f3fce7ba06';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 the_result
    bool is_simple_server
    
    `;
  }

};

module.exports = TestRequestResult;
