// Auto-generated. Do not edit!

// (in-package actionlib.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class TwoIntsResult {
  constructor() {
    this.sum = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type TwoIntsResult
    // Serialize message field [sum]
    bufferInfo = _serializer.int64(obj.sum, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type TwoIntsResult
    let tmp;
    let len;
    let data = new TwoIntsResult();
    // Deserialize message field [sum]
    tmp = _deserializer.int64(buffer);
    data.sum = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib/TwoIntsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b88405221c77b1878a3cbbfff53428d7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int64 sum
    
    `;
  }

};

module.exports = TwoIntsResult;
