# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from schunk_sdh/TactileMatrix.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TactileMatrix(genpy.Message):
  _md5sum = "ab718b6c1d4d719110707994d2e325e4"
  _type = "schunk_sdh/TactileMatrix"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 matrix_id
int16 cells_x
int16 cells_y
int16[] tactile_array
"""
  __slots__ = ['matrix_id','cells_x','cells_y','tactile_array']
  _slot_types = ['uint32','int16','int16','int16[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       matrix_id,cells_x,cells_y,tactile_array

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TactileMatrix, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.matrix_id is None:
        self.matrix_id = 0
      if self.cells_x is None:
        self.cells_x = 0
      if self.cells_y is None:
        self.cells_y = 0
      if self.tactile_array is None:
        self.tactile_array = []
    else:
      self.matrix_id = 0
      self.cells_x = 0
      self.cells_y = 0
      self.tactile_array = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_I2h.pack(_x.matrix_id, _x.cells_x, _x.cells_y))
      length = len(self.tactile_array)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(struct.pack(pattern, *self.tactile_array))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.matrix_id, _x.cells_x, _x.cells_y,) = _struct_I2h.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      end += struct.calcsize(pattern)
      self.tactile_array = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_I2h.pack(_x.matrix_id, _x.cells_x, _x.cells_y))
      length = len(self.tactile_array)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(self.tactile_array.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.matrix_id, _x.cells_x, _x.cells_y,) = _struct_I2h.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      end += struct.calcsize(pattern)
      self.tactile_array = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_I2h = struct.Struct("<I2h")
