// Generated by gencpp from file schunk_canopen_driver/HomeWithJointNamesRequest.msg
// DO NOT EDIT!


#ifndef SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEWITHJOINTNAMESREQUEST_H
#define SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEWITHJOINTNAMESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace schunk_canopen_driver
{
template <class ContainerAllocator>
struct HomeWithJointNamesRequest_
{
  typedef HomeWithJointNamesRequest_<ContainerAllocator> Type;

  HomeWithJointNamesRequest_()
    : joint_names()  {
    }
  HomeWithJointNamesRequest_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;




  typedef boost::shared_ptr< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HomeWithJointNamesRequest_

typedef ::schunk_canopen_driver::HomeWithJointNamesRequest_<std::allocator<void> > HomeWithJointNamesRequest;

typedef boost::shared_ptr< ::schunk_canopen_driver::HomeWithJointNamesRequest > HomeWithJointNamesRequestPtr;
typedef boost::shared_ptr< ::schunk_canopen_driver::HomeWithJointNamesRequest const> HomeWithJointNamesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace schunk_canopen_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/kinetic/share/control_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "587f4b1b8847cbdf153605e9cf8ebaed";
  }

  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x587f4b1b8847cbdfULL;
  static const uint64_t static_value2 = 0x153605e9cf8ebaedULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_canopen_driver/HomeWithJointNamesRequest";
  }

  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string[] joint_names\n\
";
  }

  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HomeWithJointNamesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_canopen_driver::HomeWithJointNamesRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEWITHJOINTNAMESREQUEST_H
