// Generated by gencpp from file schunk_canopen_driver/HomeWithJointNames.msg
// DO NOT EDIT!


#ifndef SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEWITHJOINTNAMES_H
#define SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEWITHJOINTNAMES_H

#include <ros/service_traits.h>


#include <schunk_canopen_driver/HomeWithJointNamesRequest.h>
#include <schunk_canopen_driver/HomeWithJointNamesResponse.h>


namespace schunk_canopen_driver
{

struct HomeWithJointNames
{

typedef HomeWithJointNamesRequest Request;
typedef HomeWithJointNamesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HomeWithJointNames
} // namespace schunk_canopen_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_canopen_driver::HomeWithJointNames > {
  static const char* value()
  {
    return "abb91c83ed030d595b2e5754d356a7f3";
  }

  static const char* value(const ::schunk_canopen_driver::HomeWithJointNames&) { return value(); }
};

template<>
struct DataType< ::schunk_canopen_driver::HomeWithJointNames > {
  static const char* value()
  {
    return "schunk_canopen_driver/HomeWithJointNames";
  }

  static const char* value(const ::schunk_canopen_driver::HomeWithJointNames&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_canopen_driver::HomeWithJointNamesRequest> should match 
// service_traits::MD5Sum< ::schunk_canopen_driver::HomeWithJointNames > 
template<>
struct MD5Sum< ::schunk_canopen_driver::HomeWithJointNamesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_canopen_driver::HomeWithJointNames >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_canopen_driver::HomeWithJointNamesRequest> should match 
// service_traits::DataType< ::schunk_canopen_driver::HomeWithJointNames > 
template<>
struct DataType< ::schunk_canopen_driver::HomeWithJointNamesRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_canopen_driver::HomeWithJointNames >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_canopen_driver::HomeWithJointNamesResponse> should match 
// service_traits::MD5Sum< ::schunk_canopen_driver::HomeWithJointNames > 
template<>
struct MD5Sum< ::schunk_canopen_driver::HomeWithJointNamesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_canopen_driver::HomeWithJointNames >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_canopen_driver::HomeWithJointNamesResponse> should match 
// service_traits::DataType< ::schunk_canopen_driver::HomeWithJointNames > 
template<>
struct DataType< ::schunk_canopen_driver::HomeWithJointNamesResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_canopen_driver::HomeWithJointNames >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeWithJointNamesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEWITHJOINTNAMES_H
