// Generated by gencpp from file schunk_canopen_driver/HomeAll.msg
// DO NOT EDIT!


#ifndef SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEALL_H
#define SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEALL_H

#include <ros/service_traits.h>


#include <schunk_canopen_driver/HomeAllRequest.h>
#include <schunk_canopen_driver/HomeAllResponse.h>


namespace schunk_canopen_driver
{

struct HomeAll
{

typedef HomeAllRequest Request;
typedef HomeAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HomeAll
} // namespace schunk_canopen_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_canopen_driver::HomeAll > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::schunk_canopen_driver::HomeAll&) { return value(); }
};

template<>
struct DataType< ::schunk_canopen_driver::HomeAll > {
  static const char* value()
  {
    return "schunk_canopen_driver/HomeAll";
  }

  static const char* value(const ::schunk_canopen_driver::HomeAll&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_canopen_driver::HomeAllRequest> should match 
// service_traits::MD5Sum< ::schunk_canopen_driver::HomeAll > 
template<>
struct MD5Sum< ::schunk_canopen_driver::HomeAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_canopen_driver::HomeAll >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_canopen_driver::HomeAllRequest> should match 
// service_traits::DataType< ::schunk_canopen_driver::HomeAll > 
template<>
struct DataType< ::schunk_canopen_driver::HomeAllRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_canopen_driver::HomeAll >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_canopen_driver::HomeAllResponse> should match 
// service_traits::MD5Sum< ::schunk_canopen_driver::HomeAll > 
template<>
struct MD5Sum< ::schunk_canopen_driver::HomeAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_canopen_driver::HomeAll >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_canopen_driver::HomeAllResponse> should match 
// service_traits::DataType< ::schunk_canopen_driver::HomeAll > 
template<>
struct DataType< ::schunk_canopen_driver::HomeAllResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_canopen_driver::HomeAll >::value();
  }
  static const char* value(const ::schunk_canopen_driver::HomeAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_CANOPEN_DRIVER_MESSAGE_HOMEALL_H
