// Auto-generated. Do not edit!

// (in-package turtle_actionlib.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class ShapeGoal {
  constructor() {
    this.edges = 0;
    this.radius = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type ShapeGoal
    // Serialize message field [edges]
    bufferInfo = _serializer.int32(obj.edges, bufferInfo);
    // Serialize message field [radius]
    bufferInfo = _serializer.float32(obj.radius, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type ShapeGoal
    let tmp;
    let len;
    let data = new ShapeGoal();
    // Deserialize message field [edges]
    tmp = _deserializer.int32(buffer);
    data.edges = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [radius]
    tmp = _deserializer.float32(buffer);
    data.radius = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'turtle_actionlib/ShapeGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3b9202ab7292cebe5a95ab2bf6b9c091';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 edges
    float32 radius
    
    `;
  }

};

module.exports = ShapeGoal;
