// Auto-generated. Do not edit!

// (in-package turtle_actionlib.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class ShapeResult {
  constructor() {
    this.interior_angle = 0.0;
    this.apothem = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type ShapeResult
    // Serialize message field [interior_angle]
    bufferInfo = _serializer.float32(obj.interior_angle, bufferInfo);
    // Serialize message field [apothem]
    bufferInfo = _serializer.float32(obj.apothem, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type ShapeResult
    let tmp;
    let len;
    let data = new ShapeResult();
    // Deserialize message field [interior_angle]
    tmp = _deserializer.float32(buffer);
    data.interior_angle = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [apothem]
    tmp = _deserializer.float32(buffer);
    data.apothem = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'turtle_actionlib/ShapeResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b06c6e2225f820dbc644270387cd1a7c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float32 interior_angle
    float32 apothem
    
    `;
  }

};

module.exports = ShapeResult;
