// Auto-generated. Do not edit!

// (in-package control_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class FollowJointTrajectoryResult {
  constructor() {
    this.error_code = 0;
    this.error_string = '';
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type FollowJointTrajectoryResult
    // Serialize message field [error_code]
    bufferInfo = _serializer.int32(obj.error_code, bufferInfo);
    // Serialize message field [error_string]
    bufferInfo = _serializer.string(obj.error_string, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type FollowJointTrajectoryResult
    let tmp;
    let len;
    let data = new FollowJointTrajectoryResult();
    // Deserialize message field [error_code]
    tmp = _deserializer.int32(buffer);
    data.error_code = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [error_string]
    tmp = _deserializer.string(buffer);
    data.error_string = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'control_msgs/FollowJointTrajectoryResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '493383b18409bfb604b4e26c676401d2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 error_code
    int32 SUCCESSFUL = 0
    int32 INVALID_GOAL = -1
    int32 INVALID_JOINTS = -2
    int32 OLD_HEADER_TIMESTAMP = -3
    int32 PATH_TOLERANCE_VIOLATED = -4
    int32 GOAL_TOLERANCE_VIOLATED = -5
    
    # Human readable description of the error code. Contains complementary
    # information that is especially useful when execution fails, for instance:
    # - INVALID_GOAL: The reason for the invalid goal (e.g., the requested
    #   trajectory is in the past).
    # - INVALID_JOINTS: The mismatch between the expected controller joints
    #   and those provided in the goal.
    # - PATH_TOLERANCE_VIOLATED and GOAL_TOLERANCE_VIOLATED: Which joint
    #   violated which tolerance, and by how much.
    string error_string
    
    
    `;
  }

};

// Constants for message
FollowJointTrajectoryResult.Constants = {
  SUCCESSFUL: 0,
  INVALID_GOAL: -1,
  INVALID_JOINTS: -2,
  OLD_HEADER_TIMESTAMP: -3,
  PATH_TOLERANCE_VIOLATED: -4,
  GOAL_TOLERANCE_VIOLATED: -5,
}

module.exports = FollowJointTrajectoryResult;
