// Auto-generated. Do not edit!

// (in-package control_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class PointHeadFeedback {
  constructor() {
    this.pointing_angle_error = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type PointHeadFeedback
    // Serialize message field [pointing_angle_error]
    bufferInfo = _serializer.float64(obj.pointing_angle_error, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type PointHeadFeedback
    let tmp;
    let len;
    let data = new PointHeadFeedback();
    // Deserialize message field [pointing_angle_error]
    tmp = _deserializer.float64(buffer);
    data.pointing_angle_error = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'control_msgs/PointHeadFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cce80d27fd763682da8805a73316cab4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float64 pointing_angle_error
    
    
    `;
  }

};

module.exports = PointHeadFeedback;
