// Auto-generated. Do not edit!

// (in-package control_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class SingleJointPositionGoal {
  constructor() {
    this.position = 0.0;
    this.min_duration = {secs: 0, nsecs: 0};
    this.max_velocity = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type SingleJointPositionGoal
    // Serialize message field [position]
    bufferInfo = _serializer.float64(obj.position, bufferInfo);
    // Serialize message field [min_duration]
    bufferInfo = _serializer.duration(obj.min_duration, bufferInfo);
    // Serialize message field [max_velocity]
    bufferInfo = _serializer.float64(obj.max_velocity, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type SingleJointPositionGoal
    let tmp;
    let len;
    let data = new SingleJointPositionGoal();
    // Deserialize message field [position]
    tmp = _deserializer.float64(buffer);
    data.position = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [min_duration]
    tmp = _deserializer.duration(buffer);
    data.min_duration = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [max_velocity]
    tmp = _deserializer.float64(buffer);
    data.max_velocity = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'control_msgs/SingleJointPositionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fbaaa562a23a013fd5053e5f72cbb35c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float64 position
    duration min_duration
    float64 max_velocity
    
    `;
  }

};

module.exports = SingleJointPositionGoal;
